package main

import (
	"fmt"

	"github.com/tequire/GoUtil/pkg/clients/jobads"
)

func main() {
	client := jobads.New("eyJhbGciOiJSUzI1NiIsImtpZCI6IjAyOTQ5NDMyMjhFRkVGQjFFQTg2QURCRDhCNkY2NzVEQjM4ODVGODYiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJBcFNVTWlqdjc3SHFocTI5aTI5blhiT0lYNFkifQ.eyJuYmYiOjE1NjIwNTE5NDQsImV4cCI6MTg3NzYyMTIwNCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5oaWdoZXJlZC5nbG9iYWwiLCJhdWQiOlsiaHR0cHM6Ly9pZGVudGl0eS5oaWdoZXJlZC5nbG9iYWwvcmVzb3VyY2VzIiwiYXBpMSIsImFwaTEuZnVsbF9hY2Nlc3MiXSwiY2xpZW50X2lkIjoiV3YyYVdRclQ2cUdhN0hLQUsiLCJzY29wZSI6WyJhcGkxIiwiYXBpMS5mdWxsX2FjY2VzcyJdfQ.kTWcSRXXIz4SsrQBduio1lntug1FY3RhALDNeXnVEx-oKc1cG1TWSew_G8jCc00KrIohJCjplH33JS39wFIESJK2erOuuSNsDpGUeThTEYSfLjbNaybU7kwKVKsRW-wyIiVv-fE9-eg7JntBCth9CkUhw1xL3jqMmADdLjD3QFRI7Gd40zPELaEn0lOtahrSBtqSqu_xTHaJKH3ggnh3cPl78MZtflS6i1dKrMQtxdh5s-V5AkHZSDrK4CZjXypNPP9IELlxaGLPjmazY-YDRYYRhOr90WuPiX-UPXmkPhJq06eHRWXPLDFhTQ5Ii0u_C_Gcf0TFh7ZzvmzQwZCxSwaLP6405eif74smrIMUMRo-TPrF8UTmMwFviOhl31NRMb9PD3BcYHM7nRUjNXeQCy2Xla8W-GSzxV-5DhuY2tEKb_Q0tq2Cw5FFOn1ev9phtbU2aaOVQq6mINThb-ZyS8fettKUtvGckbN5jtOsJ22Fnk7RPvZyItNFdnryjKXpnpvOQmNNMbB8l1X1hmq8xSP5OPLzDep2SfinfuvWMqekkW9GQXSAojYLmxjacevF4IgDqAmffuJUUemunz5qFtzfMMR8gSIpjq7LPlen3Zdhb6A8esEfiuAQVQtEnc6Jal95edHv9nRoPIgH-BcDH0jYZWpqrDo8tpoHmwMA7U0")
	client.SetProd(true)

	orgs, err := client.GetAllJobAds()
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	//fmt.Println(orgs)

	for _, school := range orgs {
		fmt.Println(school)
	}
}
